org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.daemon=false

loom.platform=forge

mod_id=chunkanimatorembeddiumcompat
mod_name=Chunk Animator Embeddium Compat
mod_group_id=com.sxilverr.chunkanimatorembeddiumcompat
mod_version=2.1
mod_license=MIT
mod_authors=Sxilverr
mod_description=Adds compatibility between the Chunk Animator mod and Embeddium/Xenon/Rubidium/Magnesium
